### ISSUE TITLE
[1.12.2] 0.1.0.4 Broken

### ISSUE THREAD

**Issue by Multi-Coder-24** [PC-Logix/OpenDisks#3]
[latest.log](https://github.com/PC-Logix/OpenDisks/files/3586865/latest.log)
Causes my game to refuse to load
Data:
Forge Version: 1.12.2-14.23.5.2838
OpenComputers version: 1.7.4.153
OpenSecurity Version: 1.0-35
OpenPrinters version: 0.1.0.7
OpenDisk Version: 0.1.0.4
Computronics Version: 1.6.6
Java: 1.8.0_221
OS: Windows 7 Home Premium.
Args: 10GB ram

**Comment by Multi-Coder-24** [comment]
Sorry Wrong Version

**Comment by CaitlynMainer** [comment]
I was just typing up that you had used the 1.7.10 build in 1.12.2 glad you figured it out.

**Comment by Multi-Coder-24** [comment]
@CaitlynMainer I am making an opencomputers based bank system and one of the required dependency is opendisk and opensecurity. May I have permission to add this information and use these mods for my lua code on a public repository. I will send the link over once it's complete

> code to a repository
